name: echos
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  authentication:
    path: ./packages/authentication
  kbeacon:
    path: ../kbeacon
  cupertino_icons:
  firebase_core:
  cloud_firestore:
  provider:  
  local_auth:
  flutter_blue_plus:
  country_icons:
  country_codes: 
  country_list:
  pinput:
  convex_bottom_bar:
  flutter_reactive_ble:
  flutter_background_service:
  device_info_plus:
  shared_preferences: ^2.0.18
  shared_preferences_android:
  shared_preferences_ios:
  shared_preferences_web:
  tuple:
  google_maps_flutter:
  image_picker:
  url_launcher:
  telephony:
  permission_handler:
  location:
  # background_location:
    
# dependency_overrides:
#   firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/alert.png
    - assets/icons/sms.png
    - assets/icons/welcome.png
    - assets/icons/register.png
    - assets/icons/connect-device.png
    - assets/icons/configure-device.png


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
