name: authentication

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_auth: 	
  cloud_firestore:
  # flutter_facebook_auth:
  # google_sign_in: 
  firebase_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true